-- 댓글

INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 85, 29, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.대박!화이팅!', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 84, 56, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?대박!ㅠㅠ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 38, 57, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.안녕하세요~화이팅!', SYSDATE - 1, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 30, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?👍', SYSDATE - 2, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 26, 38, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.오!감사합니다.', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 38, 55, '비밀댓글입니다.안녕하세요~ㅎㅎ', SYSDATE - 16, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 90, 37, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.대박!', SYSDATE - 10, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 45, 24, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~안녕하세요~화이팅!', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 61, 12, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.안녕하세요~', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 47, 25, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!!!', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 24, 35, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?화이팅!', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 27, 49, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...!!', SYSDATE - 4, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 97, 14, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?안녕하세요~', SYSDATE - 29, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 74, 58, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.👍', SYSDATE - 6, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 15, 52, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?👍', SYSDATE - 5, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 11, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!와...', SYSDATE - 3, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 61, 36, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?대박!ㅎㅎ', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 23, 12, '비밀댓글입니다.안녕하세요~!!', SYSDATE - 5, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 25, 40, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?헐감사합니다.', SYSDATE - 10, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 40, 9, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!👍', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 10, 25, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~헐감사합니다.', SYSDATE - 27, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 25, 33, '비밀댓글입니다.와...ㅠㅠ', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 91, 39, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!와...!!', SYSDATE - 4, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 77, 25, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?안녕하세요~ㅎㅎ', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 99, 49, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?안녕하세요~ㅠㅠ', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 55, 28, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!안녕하세요~👍', SYSDATE - 11, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 60, 53, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!화이팅!', SYSDATE - 7, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 1, 17, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?헐👍', SYSDATE - 12, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 51, 3, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!헐ㅠㅠ', SYSDATE - 29, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 26, 18, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?👍', SYSDATE - 9, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 83, 44, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.오!!!', SYSDATE - 21, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 20, 29, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~헐감사합니다.', SYSDATE - 7, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 14, 11, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.대박!', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 43, 20, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!안녕하세요~감사합니다.', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 56, 47, '비밀댓글입니다.대박!', SYSDATE - 5, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 39, 19, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.ㅠㅠ', SYSDATE - 27, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 63, 4, '비밀댓글입니다.대박!ㅎㅎ', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 40, 12, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?오!ㅎㅎ', SYSDATE - 21, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 5, 54, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?대박!화이팅!', SYSDATE - 4, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 62, 31, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?👍', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 27, 33, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!!!', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 93, 43, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.헐', SYSDATE - 7, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 34, 9, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!와...!!', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 54, 43, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.안녕하세요~👍', SYSDATE - 2, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 7, 57, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?와...ㅠㅠ', SYSDATE - 2, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 58, 34, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.대박!화이팅!', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 42, 58, '비밀댓글입니다.대박!감사합니다.', SYSDATE - 2, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 4, 23, '비밀댓글입니다.화이팅!', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 44, 53, '비밀댓글입니다.대박!ㅎㅎ', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 16, 42, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.대박!', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 78, 48, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.대박!👍', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 75, 29, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.오!ㅎㅎ', SYSDATE - 0, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 43, 18, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!안녕하세요~ㅎㅎ', SYSDATE - 5, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 53, 39, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!감사합니다.', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 25, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.와...ㅎㅎ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 89, 19, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.ㅎㅎ', SYSDATE - 4, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 43, 4, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?안녕하세요~', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 53, 17, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?헐', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 81, 17, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?오!', SYSDATE - 7, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 77, 54, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.오!', SYSDATE - 23, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 44, 58, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.안녕하세요~👍', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 54, 58, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.감사합니다.', SYSDATE - 10, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 60, 5, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?와...ㅠㅠ', SYSDATE - 7, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 64, 23, '비밀댓글입니다.!!', SYSDATE - 19, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 66, 23, '비밀댓글입니다.안녕하세요~!!', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 51, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!와...화이팅!', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 82, 26, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.오!감사합니다.', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 78, 14, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?헐ㅎㅎ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 3, 14, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?대박!👍', SYSDATE - 2, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 55, 53, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!안녕하세요~👍', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 79, 48, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.헐', SYSDATE - 17, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 99, 51, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.오!ㅠㅠ', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 47, 8, '비밀댓글입니다.안녕하세요~ㅎㅎ', SYSDATE - 21, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 18, 17, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.오!감사합니다.', SYSDATE - 20, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 4, 58, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.!!', SYSDATE - 27, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 84, 25, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!와...화이팅!', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 37, 59, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?', SYSDATE - 28, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 98, 4, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.오!!!', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 12, 13, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?오!ㅎㅎ', SYSDATE - 19, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 72, 42, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.대박!', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 96, 35, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~와...ㅠㅠ', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 58, 38, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?안녕하세요~감사합니다.', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 25, 9, '비밀댓글입니다.ㅎㅎ', SYSDATE - 11, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 20, 1, '비밀댓글입니다.헐ㅎㅎ', SYSDATE - 29, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 48, 4, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.ㅠㅠ', SYSDATE - 26, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 13, 19, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.👍', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 30, 35, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.안녕하세요~감사합니다.', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 79, 19, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?대박!감사합니다.', SYSDATE - 12, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 15, 34, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?와...ㅠㅠ', SYSDATE - 11, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 47, 35, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.대박!', SYSDATE - 28, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 46, 2, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.헐감사합니다.', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 34, 20, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?와...화이팅!', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 40, 34, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...화이팅!', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 29, 46, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...👍', SYSDATE - 1, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 73, 53, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?ㅠㅠ', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 17, 38, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!안녕하세요~!!', SYSDATE - 10, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 77, 54, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~와...화이팅!', SYSDATE - 29, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 93, 23, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?헐!!', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 8, 30, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?와...ㅠㅠ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 3, 33, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?대박!감사합니다.', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 82, 9, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.와...ㅎㅎ', SYSDATE - 1, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 42, 22, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?대박!', SYSDATE - 25, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 12, 25, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?안녕하세요~👍', SYSDATE - 19, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 49, 51, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!', SYSDATE - 27, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 22, 16, '비밀댓글입니다.헐감사합니다.', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 88, 30, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!ㅠㅠ', SYSDATE - 17, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 44, 34, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?대박!화이팅!', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 7, 55, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.오!', SYSDATE - 3, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 94, 41, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.와...👍', SYSDATE - 19, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 65, 37, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.오!감사합니다.', SYSDATE - 19, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 51, 25, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.와...ㅎㅎ', SYSDATE - 29, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 94, 4, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!화이팅!', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 1, 10, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?ㅠㅠ', SYSDATE - 11, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 73, 60, '비밀댓글입니다.오!ㅠㅠ', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 93, 45, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?와...ㅠㅠ', SYSDATE - 9, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 89, 59, '좋은 정보 감사합니다! 당장 적용해 봐야겠네요.대박!ㅠㅠ', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 59, 5, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...👍', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 55, 23, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?헐!!', SYSDATE - 3, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 22, 9, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~오!감사합니다.', SYSDATE - 28, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 23, 5, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?헐!!', SYSDATE - 17, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 51, 11, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...화이팅!', SYSDATE - 15, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 13, 14, '비밀댓글입니다.대박!ㅠㅠ', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 80, 36, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?대박!ㅠㅠ', SYSDATE - 22, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 31, 37, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?안녕하세요~화이팅!', SYSDATE - 9, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 35, 24, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.안녕하세요~ㅠㅠ', SYSDATE - 11, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 88, 2, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~ㅎㅎ', SYSDATE - 18, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 78, 19, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.ㅎㅎ', SYSDATE - 13, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 64, 3, '비밀댓글입니다.오!ㅎㅎ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 55, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.와...!!', SYSDATE - 28, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 69, 18, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?안녕하세요~화이팅!', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 62, 17, '혹시 스프링부트 버전은 몇 점 대 사용하셨나요?와...감사합니다.', SYSDATE - 27, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 28, 41, '저도 같은 에러 때문에 며칠 고생했는데, 덕분에 해결했습니다!ㅠㅠ', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 99, 11, '비밀댓글입니다.대박!👍', SYSDATE - 21, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 10, 6, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?와...ㅎㅎ', SYSDATE - 26, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 93, 14, '비밀댓글입니다.안녕하세요~화이팅!', SYSDATE - 19, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 71, 59, '저도 같이 스터디 참여하고 싶은데 아직 자리 있나요?안녕하세요~감사합니다.', SYSDATE - 28, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 42, 13, '오늘도 좋은 글 잘 읽고 갑니다. 화이팅!안녕하세요~ㅠㅠ', SYSDATE - 3, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 5, 34, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.오!화이팅!', SYSDATE - 24, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 51, 37, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?감사합니다.', SYSDATE - 6, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 24, 9, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?ㅎㅎ', SYSDATE - 14, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 44, 57, '이 방식 말고 다른 방법으로 구현해 보는 건 어떨까요?와...ㅎㅎ', SYSDATE - 0, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 64, 41, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.👍', SYSDATE - 0, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 21, 25, '링크가 안 열리는 것 같아요. 확인 한 번 부탁드립니다~안녕하세요~', SYSDATE - 25, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 88, 30, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.안녕하세요~화이팅!', SYSDATE - 8, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 72, 28, '질문 있습니다! 여기서 이 메서드를 쓴 특별한 이유가 있을까요?오!', SYSDATE - 21, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 21, 4, '와... 코드가 진짜 깔끔하네요. 많이 배워갑니다.오!감사합니다.', SYSDATE - 10, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 3, 43, '비밀댓글입니다.와...👍', SYSDATE - 23, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 44, 52, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.감사합니다.', SYSDATE - 16, null, 0);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 41, 60, '이거 퍼가도 될까요? 출처는 꼭 남기겠습니다.헐👍', SYSDATE - 15, null, 1);
INSERT INTO tbl_Comment (seq_comment, seq_user, seq_note, detail, regdate, fixdate, status) VALUES (seq_comment.nextval, 40, 50, '오라클 조인할 때 이 부분 항상 헷갈렸는데 정리 최고입니다.헐감사합니다.', SYSDATE - 18, null, 0);


-- 삭제
delete
from tbl_Comment
where seq_note between 1 and 62;

-- 시퀀스 1부터 시작
ALTER SEQUENCE seq_comment RESTART START WITH 1;

--확인
select * from TBL_COMMENT;

--저장
commit ;